import StyledComponentsRegistry from "./components/StyledComponentsRegistry";
import GlobalStyle from "./GlobalStyle";

export const metadata = {
  title: 'MC Mod Board',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
       <GlobalStyle />
      <body>{children}</body>
      </StyledComponentsRegistry>
    </html>
  )
}
